
import './styles/globals.css'
import localFont from 'next/font/local'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const vazirmatn = localFont({
    src: [
        {
            path: './fonts/Vazirmatn-Regular.woff2',
            weight: '400',
            style: 'normal',
        },

        {
            path: './fonts/Vazirmatn-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],

    variable: '--font-vazirmatn',
})

export default function RootLayout({ children }) {
    return (
        <html lang="fa" className={vazirmatn.variable}>
            <head>
                <link rel="stylesheet" href="/font-awesome-7.2.0/css/all.css" />
            </head>

            <body className="bg-primary/5">
                
                <div>{children}</div>
            </body>
        </html>
    )
}
