import '@/app/global.css'
import { Navbar } from '@/components/navbar'

import localFont from 'next/font/local'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const vazirmatn = localFont({
    src: [
        {
            path: './fonts/webfonts/Vazirmatn-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/webfonts/Vazirmatn-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],

    variable: '--font-vazirmatn',
})

export default function RootLayout({ children }) {
    return (
        <html lang="fa" className={vazirmatn.variable}>
            <head>
                <link
                    rel="stylesheet"
                    href="/font-awesome-4.7.0/css/font-awesome.min.css"
                />
            </head>
            <body>
                <Navbar />

                {children}
            </body>
        </html>
    )
}
